import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";
import { ThemeProvider } from "@/components/theme-provider";


const montserratSans = Montserrat({
  weight:'400',
  subsets: ["latin"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserratSans.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
